plugins {
    id "com.android.application"
}

android {
    namespace "com.olivierh.teamg1demo"
    compileSdk 36

    defaultConfig {
        applicationId "com.olivierh.teamg1demo"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation files("libs/teamg1demo.aar")
}
